spring:
  profiles:
    include: kafka
  application:
    name: rate-limiter-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/rate_limiter
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
